### ISSUE TITLE
classes missing

### ISSUE THREAD

**Issue by hussnain** [Yubico/yubikey-neo-demo#3]
YubicoClient and  YubicoResponse classes are missing

**Comment by klali** [comment]
Those classes are part of the yubico-java-client that's a dependency. If you build with maven dependency resolution should be automatic.

**Comment by hussnain** [comment]
yea got it klali v.thanks.i have to discuss some things regarding yubico authentication on Android . plz provide your email so that we can talk

**Comment by klali** [comment]
you can reach me at klas@yubico.com
